# --- Required options --- #
# background link https://github.com/pages-themes/dinky

title: Geo Numeracy
theme: jekyll-theme-dinky
# theme: jekyll-theme-cayman
show_downloads: true

# Name of website
name: geonumeracy
description: Working with geometry using numpy, part II.

# [npg](voronoi2.png)
# Your name to show in the footer
author: Dan Patterson
  
url: "https://dan-patterson.github.io/geonumeracy"

# url: https://github.com/Dan-Patterson "https://dan-patterson.github.io/geonumeracy"
# exclude:
# --- Logo --- #

# Image to show in the navigation bar - works best with a square image
# Remove this parameter if you don't want an image in the navbar
# avatar: "/assets/img/avatar-icon.png"

# If you want to have an image logo in the top-left corner instead of having the title of the website,
# then specify the following parameter
#title-img: /path/to/image

# kramdown
markdown: GFM

# Alternatively, the navbar, footer, and page background can be set to an image
# instead of colour

#navbar-img: "/assets/img/bgimage.png"
#footer-img: "/assets/img/bgimage.png"
#page-img: "/assets/img/bgimage.png"
plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Gems
#gems:
#  - jekyll-paginate
# --- reference ---
# https://github.com/daattali/beautiful-jekyll/blob/master/_config.yml
